services:
  python:
    container_name: python_app
    image: dotweb.test/python
    build:
      context: ./
      dockerfile: ./infrastructure/docker/Dockerfile
      target: app
      args:
        HF_TOKEN: ${HF_TOKEN}
        MODEL_NAME: ${MODEL_NAME}
    restart: on-failure
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - MODEL_NAME=${MODEL_NAME}
      - BLUEVI_GPT=${BLUEVI_GPT}

  nginx:
    container_name: python_web
    image: dotweb.test/nginx:python
    depends_on:
      - python
    restart: on-failure
    networks:
      - internal
      - dotweb.test
    volumes:
      - .:/app

networks:
  internal:
    name: web_internal
  dotweb.test:
    name: dotweb.test
    external: true