services:
  python:
    container_name: gpt_python
    image: dotweb.test/python
    build:
      context: ./
      dockerfile: ./infrastructure/docker/Dockerfile
      target: app
      secrets:
        - hf_token
        - model_name
    restart: on-failure
    networks:
      - internal
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - MODEL_NAME=${MODEL_NAME}
      - BLUEVI_GPT=${BLUEVI_GPT}
  nginx:
    container_name: gpt_web
    image: dotweb.test/nginx:python
    depends_on:
      - python
    restart: on-failure
    networks:
      - internal
      - dotweb.test
    volumes:
      - .:/app

secrets:
  hf_token:
    environment: HF_TOKEN
  model_name:
    environment: MODEL_NAME

networks:
  internal:
    name: gpt_internal
  dotweb.test:
    name: dotweb.test
    external: true